name: deploy-pterodactyl-html
run-name: ${{ github.actor }} is deploying Pterodactyl

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PHP & dependencies
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt update
          sudo apt install -y php8.1 php8.1-cli php8.1-mbstring php8.1-xml php8.1-curl php8.1-mysql php8.1-bcmath php8.1-zip unzip curl git nginx

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Setup Pterodactyl panel (partial)
        run: |
          mkdir -p pterodactyl/public
          cp -r public/* pterodactyl/public/
          echo "Fake deployment complete"

      - name: Deploy to GitHub Pages (for demo HTML)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pterodactyl/public
